name: free_play
description: Free to Play Game Database

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  pmvvm: ^4.0.1
  carousel_slider: ^4.1.1
  http: ^0.13.4
  toast: ^0.2.9
  google_fonts: ^2.2.0
  flutter_svg: ^1.1.1+1
  persistent_bottom_nav_bar: ^4.0.2
  dio: ^4.0.6
  flutter_twitch_player: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:

    - assets/images/
